
results_save: False
results_dir: ''
mcts_saved_dir: ''
load_results: False
use_gpu: True
explainer_name: 'ctms5'
explainer_ckpt_dir: ''
debug_mode: False
cmomcts_saved_dir: ''

param:
  wikipedia:
    explanation_level: 'event'
    verbose: True
    train_epochs:  20 # 20
    threshold_num: 20
    reg_coefs:
      - 0.5
      - 0.1
    batch_size: 16
    lr: 1e-1
  reddit:
    explanation_level: 'event'
    verbose: True
    train_epochs: 15 # 20
    threshold_num: 20
    reg_coefs:
      - 0.5
      - 0.1
    batch_size: 16
    lr: 1e-1
  simulate_v1:
    explanation_level: 'event'
    verbose: True
    train_epochs: 15 # 20, 30, 
    threshold_num: 20
    reg_coefs:
      - 0.5
      - 0.1
    batch_size: 16
    lr: 1e-1
  simulate_v2:
    explanation_level: 'event'
    verbose: True
    train_epochs: 12 # 20, 30, 
    threshold_num: 20
    reg_coefs:
      - 0.5
      - 0.1
    batch_size: 16
    lr: 1e-1
  
  


  
